name: Lines of code in the repository
run-name: Lines of code in REPO
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Lines of code
        run: |
          git ls-files --exclude-standard -- ':!:**/*.mmdb' ':!:**/cities_optimised_load.*' ':!:**/*.json' | xargs wc -l
